name: "Cloud Run - Source code to GCP"

on:
  push:
    branches: 
      - feature/andrew-testing

env: 
  WORKLOAD_IDENTITY_PROVIDER: "projects/937611148812/locations/global/workloadIdentityPools/cloud-run-oidc/providers/test2"
  SERVICE_ACCOUNT: "cloud-run-sa@cloud-run-demo-379520.iam.gserviceaccount.com"
  SOURCE_CODE_DIRECTORY: helloworld-csharp
  ARTIFACT_REGISTRY: us-central1-docker.pkg.dev/cloud-run-demo-379520/cloud-run-source-deploy

jobs: 
  authenticate-and-deploy: 
    runs-on: ubuntu-latest
    permissions: 
      contents: 'read'
      id-token: 'write'
    steps: 
    - name: "Checkout"
      uses: actions/checkout@v3

    - id: "pack-download"
      name: "Download Buildpack Package"
      run: |
        sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
        sudo apt-get update
        sudo apt-get install pack-cli

    - id: 'authenticate'
      name: "Authenticate to Google Cloud"
      uses: google-github-actions/auth@v1
      with: 
        token_format: access_token
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: '${{ env.SERVICE_ACCOUNT }}'
        access_token_lifetime: 300s

    - id: 'run-buildpack'
      name: "Test with Buildpack"
      run: |
        pack build --builder=gcr.io/buildpacks/builder ${{ env.SOURCE_CODE_DIRECTORY }}

    - id: 'docker-auth'
      uses: 'docker/login-action@v1'
      with: 
        registry: '${{ env.ARTIFACT_REGISTRY }}'
        username: 'oauth2accesstoken'
        password: '${{ steps.authenticate.outputs.access_token }}'
    - id: 'build-and-push'
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: helloworld-csharp:latest

    - id: 'push'
      name: "Docker push"
      run: |
        docker push helloworld-csharp

    # - id: 'deploy'
    #   name: "Deploy Cloud Run"
    #   uses: google-github-actions/deploy-cloudrun@v0
    #   with: 
    #     service: "app"
    #     source: ./{{ env.SOURCE_CODE_DIRECTORY }}
    #     env_vars: |
    #       INSTANCE_CONNECTION_NAME=test
    #     secrets: |
    #       DB_USER=secret-key-1:latest
    #       DB_PASSWORD=secret-key-1:latest
    #       DB_NAME=secret-key-1:latest


