name: "Cloud Run - Source code to GCP"

on:
  push:
    branches: 
      - feature/andrew-testing

env: 
  WORKLOAD_IDENTITY_PROVIDER: "projects/937611148812/locations/global/workloadIdentityPools/cloud-run-oidc/providers/test2"
  SERVICE_ACCOUNT: "cloud-run-sa@cloud-run-demo-379520.iam.gserviceaccount.com"

jobs: 
  authenticate-and-deploy: 
    runs-on: ubuntu-latest
    permissions: 
      contents: 'read'
      id-token: 'write'
    steps: 
    - uses: actions/checkout@v3

    - id: 'authenticate'
      name: "Authenticate to Google Cloud"
      uses: google-github-actions/auth@v1
      with: 
        token_format: access_token
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: '${{ env.SERVICE_ACCOUNT }}'
        access_token_lifetime: 300s
    - id: 'deploy'
      name: "Deploy Cloud Run"
      uses: google-github-actions/deploy-cloudrun@v0
      with: 
        service: "app"
        source: ./helloworld-csharp
        env_vars: |
          FOO=bar
          TEST=ing
        secrets: |
          KEY1=secret-key-1:latest
