name: "Cloud Run - Source code to GCP"

on:
  push: 

env: 
  WORKLOAD_IDENTITY_PROVIDER: "projects/937611148812/locations/global/workloadIdentityPools/cloud-run-oidc/providers/test2"
  SERVICE_ACCOUNT: "cloud-run-sa@cloud-run-demo-379520.iam.gserviceaccount.com"

jobs: 
  authenticate:
    runs-on: ubuntu-latest
    permissions: 
      contents: 'read'
      id-token: 'write'
    steps: 
    - uses: actions/checkout@v3

    - id: 'authenticate'
      name: "Authenticate to Google Cloud"
      uses: google-github-actions/auth@v1
      with: 
        token_format: access_token
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: '${{ env.SERVICE_ACCOUNT }}'
        access_token_lifetime: 300
  deploy:
    needs: [authenticate]
    runs-on: ubuntu-latest
    steps:
    - id: 'deploy'
      name: "Deploy Cloud Run"
      uses: google-github-actions/deploy-cloudrun@v0
      with: 
        service: "hello-cloud-run"
        source: ./deployment-pattern/src