name: "Cloud Run - Source code to GCP"

on:
  push:
    branches: 
      - feature/andrew-testing

env: 
  WORKLOAD_IDENTITY_PROVIDER: "projects/937611148812/locations/global/workloadIdentityPools/cloud-run-oidc/providers/test2"
  SERVICE_ACCOUNT: "cloud-run-sa@cloud-run-demo-379520.iam.gserviceaccount.com"

jobs: 
  authenticate-and-deploy: 
    runs-on: ubuntu-latest
    permissions: 
      contents: 'read'
      id-token: 'write'
    steps: 
    - name: "Checkout"
      uses: actions/checkout@v3

    - id: 'authenticate'
      name: "Authenticate to Google Cloud"
      uses: google-github-actions/auth@v1
      with: 
        token_format: access_token
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: '${{ env.SERVICE_ACCOUNT }}'
        access_token_lifetime: 300s
    - id: "download pack"
      run: |
      (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.28.0/pack-v0.28.0-macos.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)

    - id: 'buildpack'
      name: "Test with Buildpack"
      run: |
       pack build --builder=gcr.io/buildpacks/builder ./helloworld-csharp

    - id: 'deploy'
      name: "Deploy Cloud Run"
      uses: google-github-actions/deploy-cloudrun@v0
      with: 
        service: "app"
        source: ./helloworld-csharp
        env_vars: |
          INSTANCE_CONNECTION_NAME=test
        secrets: |
          DB_USER=secret-key-1:latest
          DB_PASSWORD=secret-key-1:latest
          DB_NAME=secret-key-1:latest


